### ISSUE TITLE
errors out about dlls not being win application 

### ISSUE THREAD

**Issue by 2blackbar** [james-things/bitsandbytes-prebuilt-all_arch#4]
Also why the file is 22mb if the 16 version of dll is about 6mb

Inferred yaml: v1-inference.yaml, attn: sd1, prediction_type: epsilon
 * Training Text and Unet *
Traceback (most recent call last):
  File "F:\ED\EveryDream2trainer\train.py", line 950, in <module>
    main(args)
  File "F:\ED\EveryDream2trainer\train.py", line 503, in main
    import bitsandbytes as bnb
  File "F:\ED\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\__init__.py", line 5, in <module>
    from .optim import adam
  File "F:\ED\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 5, in <module>
    from .adam import Adam, Adam8bit, Adam32bit
  File "F:\ED\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\optim\adam.py", line 11, in <module>
    from bitsandbytes.optim.optimizer import Optimizer2State
  File "F:\ED\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\optim\optimizer.py", line 6, in <module>
    import bitsandbytes.functional as F
  File "F:\ED\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    lib = ct.cdll.LoadLibrary(os.path.dirname(__file__) + '/libbitsandbytes.so')
  File "C:\Users\BAZO\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\BAZO\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by james-things** [comment]
In order to use this Windows dll in something like EveryDream2, you will need to patch some files in the bitsandbytes library folder. I believe that the three .py files in this directory should do the trick: https://github.com/d8ahazard/sd_dreambooth_extension/tree/main/bitsandbytes_windows

You may need to check in the existing folders to see where they belong - iirc it is between the library root `/` and `/cuda_setup` but I am not positive. Each one should replace an existing file.

In your case, the path to your existing bitsandbytes library is `F:\ED\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\`, so this is where you want to be replacing the files. You will want to make sure that the windows dll is in that folder too.

The dll in the folder that I linked above should be a copy of the latest one from this repo, or at least one of the versions from this repo, so you can always just copy eveything from there. 

Let me know how you make out, I was able to get it working when I tried out ED2 myself. :)
